### ISSUE TITLE
Update time ended value on running log?

### ISSUE THREAD

**Issue by mateowatson** [mateowatson/timetracker#76]
When a log has no end time (aka the currently running log in the timer), it used to display nothing in the logs table in the end time cell, but now it displays the current time (as of page load). I feel like that's a little confusing. Should it update in JS as well, or maybe have some kind of marker indicationg it has not ended yet?

**Comment by blakewatson** [comment]
This is a bug. In the `Utils` function that converts the datetime to HTML, `formatted_datetime_to_html`, it should early return if it is passed an empty `$formatted_date`. Currently, it goes ahead and tries to create a date object, which ends up being the current date and time.

At least that's what I figure is happening. I'm not testing it right now because it's 2 a.m. 😴
